"use client";

import { useState } from "react";
import { BarChart, Play, History, Search, FileText, Table, Eye, Download, ChevronLeft, ChevronRight } from "lucide-react";
import { getCurrentUser } from "@/lib/store";

interface Report {
  id: string;
  name: string;
  dateRange: string;
  generatedDate: string;
  generatedBy: string;
  status: "Ready" | "Processing";
  type: "PDF" | "Excel" | "CSV";
  icon: "FileText" | "Table";
}

const INITIAL_REPORTS: Report[] = [
  {
    id: "1",
    name: "Monthly Tax Collection Summary",
    dateRange: "Oct 2023",
    generatedDate: "24 Nov 2023, 10:30 AM",
    generatedBy: "System Auto",
    status: "Ready",
    type: "PDF",
    icon: "FileText"
  },
  {
    id: "2",
    name: "Grievance Resolution Q3 Data",
    dateRange: "Jul - Sep 2023",
    generatedDate: "22 Nov 2023, 14:15 PM",
    generatedBy: "Admin User",
    status: "Ready",
    type: "Excel",
    icon: "Table"
  }
];

export default function Reports() {
  const [reports, setReports] = useState<Report[]>(INITIAL_REPORTS);
  const [isGenerating, setIsGenerating] = useState(false);
  const [category, setCategory] = useState("Public Works");
  const [format, setFormat] = useState("PDF Document (.pdf)");

  const handleGenerate = (e: React.FormEvent) => {
    e.preventDefault();
    if (isGenerating) return;
    
    setIsGenerating(true);
    const user = getCurrentUser();
    
    const newReport: Report = {
      id: Math.random().toString(),
      name: `${category} Custom Report`,
      dateRange: "Custom Range",
      generatedDate: "Just now",
      generatedBy: user ? user.name : "You",
      status: "Processing",
      type: format.includes("Excel") ? "Excel" : format.includes("CSV") ? "CSV" : "PDF",
      icon: format.includes("Excel") || format.includes("CSV") ? "Table" : "FileText"
    };

    setReports([newReport, ...reports]);

    // Simulate processing time
    setTimeout(() => {
      setReports((prev) => 
        prev.map(r => r.id === newReport.id ? { ...r, status: "Ready" } : r)
      );
      setIsGenerating(false);
    }, 3000);
  };

  const handleDownload = (report: Report) => {
    const content = `Report: ${report.name}\nDate Range: ${report.dateRange}\nGenerated Date: ${report.generatedDate}\nGenerated By: ${report.generatedBy}\nType: ${report.type}`;
    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${report.name.replace(/\s+/g, "_").toLowerCase()}_report.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <main className="flex-1 p-margin-mobile md:p-margin-desktop bg-background min-h-screen pb-32 md:pb-margin-desktop">
      {/* Page Header */}
      <header className="mb-stack-lg pt-4 md:pt-0">
        <h1 className="font-heading font-semibold text-[32px] leading-[40px] text-on-surface">Reports</h1>
        <p className="font-sans text-[16px] text-on-surface-variant mt-1">अहवाल व्यवस्थापन (Report Management)</p>
      </header>
      <div className="max-w-container-max mx-auto space-y-stack-md">
        {/* Generate New Report Section */}
        <section className="bg-surface rounded-lg border border-outline-variant p-6 shadow-sm relative overflow-hidden">
          {/* Decorative background element */}
          <div className="absolute top-0 right-0 w-64 h-64 bg-surface-container rounded-full blur-3xl -mr-32 -mt-32 opacity-50 pointer-events-none"></div>
          <div className="relative z-10">
            <h2 className="font-heading font-semibold text-[20px] text-on-surface mb-6 flex items-center gap-2">
              <BarChart className="text-primary w-5 h-5" />
              Generate New Report
              <span className="text-[14px] font-sans text-on-surface-variant ml-2 font-normal">(नवीन अहवाल तयार करा)</span>
            </h2>
            <form className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6" onSubmit={handleGenerate}>
              {/* Category Filter */}
              <div className="flex flex-col gap-2">
                <label className="font-sans text-[14px] font-medium text-on-surface" htmlFor="report_category">
                  Report Category
                  <span className="block text-[12px] text-on-surface-variant font-normal">अहवाल श्रेणी</span>
                </label>
                <select 
                  value={category}
                  onChange={(e) => setCategory(e.target.value)}
                  className="w-full rounded bg-surface border-outline-variant focus:border-primary focus:ring-1 focus:ring-primary text-on-surface font-sans text-[16px] py-2" 
                  id="report_category"
                >
                  <option>Select Category...</option>
                  <option>Tax Collection</option>
                  <option>Grievance Resolution</option>
                  <option>Public Works</option>
                  <option>Health & Sanitation</option>
                </select>
              </div>
              {/* Start Date */}
              <div className="flex flex-col gap-2">
                <label className="font-sans text-[14px] font-medium text-on-surface" htmlFor="start_date">
                  Start Date
                  <span className="block text-[12px] text-on-surface-variant font-normal">सुरुवातीची तारीख</span>
                </label>
                <input required className="w-full rounded bg-surface border-outline-variant focus:border-primary focus:ring-1 focus:ring-primary text-on-surface font-sans text-[16px] py-2" id="start_date" type="date"/>
              </div>
              {/* End Date */}
              <div className="flex flex-col gap-2">
                <label className="font-sans text-[14px] font-medium text-on-surface" htmlFor="end_date">
                  End Date
                  <span className="block text-[12px] text-on-surface-variant font-normal">शेवटची तारीख</span>
                </label>
                <input required className="w-full rounded bg-surface border-outline-variant focus:border-primary focus:ring-1 focus:ring-primary text-on-surface font-sans text-[16px] py-2" id="end_date" type="date"/>
              </div>
              {/* Format */}
              <div className="flex flex-col gap-2">
                <label className="font-sans text-[14px] font-medium text-on-surface" htmlFor="report_format">
                  Format
                  <span className="block text-[12px] text-on-surface-variant font-normal">स्वरूप</span>
                </label>
                <select 
                  value={format}
                  onChange={(e) => setFormat(e.target.value)}
                  className="w-full rounded bg-surface border-outline-variant focus:border-primary focus:ring-1 focus:ring-primary text-on-surface font-sans text-[16px] py-2" 
                  id="report_format"
                >
                  <option>PDF Document (.pdf)</option>
                  <option>Excel Spreadsheet (.xlsx)</option>
                  <option>CSV Data (.csv)</option>
                </select>
              </div>
              {/* Action Area */}
              <div className="col-span-1 md:col-span-2 lg:col-span-4 flex justify-end mt-4 pt-4 border-t border-outline-variant">
                <button 
                  disabled={isGenerating}
                  className="bg-primary text-on-primary font-sans text-[14px] font-medium px-6 py-2.5 rounded hover:bg-primary-container hover:text-on-primary-container transition-colors shadow-sm flex items-center gap-2 disabled:opacity-50" 
                  type="submit"
                >
                  <Play className="text-[18px] w-4 h-4" />
                  {isGenerating ? "Generating..." : "Generate Report"}
                </button>
              </div>
            </form>
          </div>
        </section>

        {/* Recently Generated Reports List */}
        <section className="bg-surface rounded-lg border border-outline-variant shadow-sm overflow-hidden">
          <div className="p-6 border-b border-outline-variant flex justify-between items-center bg-surface-container-lowest">
            <h2 className="font-heading font-semibold text-[20px] text-on-surface flex items-center gap-2">
              <History className="text-secondary w-5 h-5" />
              Recent Reports
              <span className="text-[14px] font-sans text-on-surface-variant ml-2 font-normal">(अलीकडील अहवाल)</span>
            </h2>
            <div className="relative">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-on-surface-variant w-4 h-4" />
              <input className="pl-10 pr-4 py-2 rounded border-outline-variant text-[14px] font-sans focus:border-primary focus:ring-1 focus:ring-primary bg-surface w-64" placeholder="Search reports..." type="text"/>
            </div>
          </div>
          <div className="overflow-x-auto">
            <table className="w-full text-left border-collapse">
              <thead>
                <tr className="bg-surface-container-low border-b border-outline-variant">
                  <th className="p-4 font-sans text-[14px] font-medium text-on-surface-variant">Report Name <span className="block text-[11px] font-normal">अहवालाचे नाव</span></th>
                  <th className="p-4 font-sans text-[14px] font-medium text-on-surface-variant">Generated Date <span className="block text-[11px] font-normal">तारीख</span></th>
                  <th className="p-4 font-sans text-[14px] font-medium text-on-surface-variant">Generated By <span className="block text-[11px] font-normal">तयार करणारा</span></th>
                  <th className="p-4 font-sans text-[14px] font-medium text-on-surface-variant">Status <span className="block text-[11px] font-normal">स्थिती</span></th>
                  <th className="p-4 font-sans text-[14px] font-medium text-on-surface-variant text-right">Actions <span className="block text-[11px] font-normal text-right">कृती</span></th>
                </tr>
              </thead>
              <tbody className="divide-y divide-outline-variant bg-surface">
                {reports.map((report) => (
                  <tr key={report.id} className={`hover:bg-surface-container-lowest transition-colors ${report.status === "Processing" ? "bg-surface-container-lowest/50" : ""}`}>
                    <td className="p-4">
                      <div className="flex items-center gap-3">
                        <div className={`w-8 h-8 rounded flex items-center justify-center ${
                          report.status === "Processing" ? "bg-surface-container text-on-surface-variant opacity-50" : 
                          report.type === "PDF" ? "bg-error-container text-on-error-container" : 
                          "bg-secondary-container text-on-secondary-container"
                        }`}>
                          {report.icon === "Table" ? <Table className="w-4 h-4" /> : <FileText className="w-4 h-4" />}
                        </div>
                        <div>
                          <p className="font-sans text-[16px] font-medium text-on-surface">{report.name}</p>
                          <p className="font-sans text-[12px] text-on-surface-variant">{report.dateRange}</p>
                        </div>
                      </div>
                    </td>
                    <td className="p-4 font-sans text-[14px] text-on-surface">{report.generatedDate}</td>
                    <td className="p-4 font-sans text-[14px] text-on-surface">{report.generatedBy}</td>
                    <td className="p-4">
                      {report.status === "Processing" ? (
                        <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-[12px] font-medium bg-surface-variant text-on-surface-variant">
                          <span className="w-1.5 h-1.5 rounded-full bg-primary mr-1.5 animate-pulse"></span>
                          Processing
                        </span>
                      ) : (
                        <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-[12px] font-medium bg-surface-container-highest text-on-surface-variant">
                          Ready
                        </span>
                      )}
                    </td>
                    <td className="p-4 text-right space-x-2">
                      <button 
                        className={`p-2 rounded inline-flex items-center justify-center transition-colors ${report.status === "Processing" ? "text-outline-variant cursor-not-allowed" : "text-primary hover:text-primary-container hover:bg-surface-container-low"}`} 
                        disabled={report.status === "Processing"} 
                        title="View"
                      >
                        <Eye className="w-5 h-5" />
                      </button>
                      <button 
                        className={`p-2 rounded inline-flex items-center justify-center transition-colors ${report.status === "Processing" ? "text-outline-variant cursor-not-allowed" : "text-primary hover:text-primary-container hover:bg-surface-container-low"}`} 
                        disabled={report.status === "Processing"} 
                        title={`Download ${report.type}`}
                        onClick={() => handleDownload(report)}
                      >
                        <Download className="w-5 h-5" />
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          {/* Pagination */}
          <div className="p-4 border-t border-outline-variant bg-surface flex items-center justify-between">
            <span className="font-sans text-[14px] text-on-surface-variant">Showing 1 to {reports.length} entries</span>
            <div className="flex gap-1">
              <button className="w-8 h-8 rounded flex items-center justify-center border border-outline-variant text-on-surface hover:bg-surface-container-low transition-colors disabled:opacity-50" disabled>
                <ChevronLeft className="w-4 h-4" />
              </button>
              <button className="w-8 h-8 rounded flex items-center justify-center bg-primary text-on-primary font-sans text-[14px]">1</button>
              <button className="w-8 h-8 rounded flex items-center justify-center border border-outline-variant text-on-surface hover:bg-surface-container-low transition-colors disabled:opacity-50" disabled>
                <ChevronRight className="w-4 h-4" />
              </button>
            </div>
          </div>
        </section>
      </div>
    </main>
  );
}
